#!/bin/bash

echo "🔐 Hugging Face Token Setup"
echo "=============================="
echo ""
echo "Step 1: Get your HF Access Token"
echo "   👉 Go to: https://huggingface.co/settings/tokens"
echo "   👉 Click 'New token'"
echo "   👉 Name: 'HireScope Deploy'"
echo "   👉 Type: 'Write' (needed for pushing)"
echo "   👉 Click 'Generate'"
echo "   👉 Copy the token"
echo ""
echo "Step 2: Configure Git with Token"
echo "   Run this command (replace YOUR_TOKEN):"
echo ""
echo "   git remote remove hf"
echo "   git remote add hf https://YOUR_USERNAME:YOUR_TOKEN@huggingface.co/spaces/Arcadian27/hirescope_backend"
echo ""
echo "Step 3: Push to HF"
echo "   git subtree push --prefix backend hf main"
echo ""
echo "=============================="
echo "📖 Full guide: https://huggingface.co/docs/hub/security-tokens"
