#!/bin/bash

echo "🤗 Hugging Face Spaces Setup"
echo "=============================="
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to: https://huggingface.co/new-space"
echo "2. Create a new Space:"
echo "   - Name: hirescope-backend"
echo "   - SDK: Docker ⭐"
echo "   - License: MIT"
echo "   - Click 'Create Space'"
echo ""
echo "3. After creating, you'll see your Space URL like:"
echo "   https://huggingface.co/spaces/YOUR_USERNAME/hirescope-backend"
echo ""
echo "4. Copy your Space's Git URL (it will look like):"
echo "   https://huggingface.co/spaces/YOUR_USERNAME/hirescope-backend"
echo ""
echo "5. Then run these commands:"
echo ""
echo "   # Add Hugging Face remote (replace YOUR_USERNAME)"
echo "   git remote add hf https://huggingface.co/spaces/YOUR_USERNAME/hirescope-backend"
echo ""
echo "   # Push backend folder to HF Space"
echo "   git subtree push --prefix backend hf main"
echo ""
echo "=============================="
echo "📝 Need your HF username? Check: https://huggingface.co/settings/account"
